---
title: "data_present_3mar21"
author: "Tobias"
date: "3/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r add packages and data, echo=FALSE}


setwd("C:/Users/obiew/Desktop/vannette/growthassay_2021")

library(grofit)
library(ggplot2)
library(gridExtra)
library(tidyverse)
library(data.table)
library(growthcurver)

parms_2xaa <- read.csv("output/2xaa_summary.csv")
parms_medsug <- read.csv("output/low_sugar_summary.csv")
parms_highaa <- read.csv("output/highaa_summary.csv")




labels <- read.csv("input/2021labels.csv")
d <- read.csv("input/2x_aa_feb24_2021_cleaned.csv")
d <- rename(d, c("time" = "Time"))
melt1<-reshape2::melt(d, id.vars = "time", variable.name = "well")
graph_2xaa <- merge(melt1, labels, by="well", incomparables=NA)
graph_2xaa$microbe <- as.factor(graph_2xaa$microbe)
graph_2xaa$treatment <- as.factor(graph_2xaa$treatment)

graph_2xaa$time <- (seq.int(nrow(d)))*15

graph_2xaa<- graph_2xaa %>%
  group_by(well) %>% 
  mutate(value_adjust=value- first(value))



#now for high aa


d2 <- read.csv("input/10x_aa_feb15_2021_cleaned.csv")
d2 <- rename(d2, c("time" = "Time"))
melt1<-reshape2::melt(d2, id.vars = "time", variable.name = "well")
graph_highaa <- merge(melt1, labels, by="well", incomparables=NA)
graph_highaa$microbe <- as.factor(graph_highaa$microbe)
graph_highaa$treatment <- as.factor(graph_highaa$treatment)

graph_highaa$time <- (seq.int(nrow(d2)))*15

graph_highaa<- graph_highaa %>%
  group_by(well) %>% 
  mutate(value_adjust=value- first(value))


#then 2x sugar
d3 <- read.csv("input/lowsugar_feb11_2021_cleaned.csv")
d3 <- rename(d3, c("time" = "Time"))
melt1<-reshape2::melt(d3, id.vars = "time", variable.name = "well")
graph_medsug <- merge(melt1, labels, by="well", incomparables=NA)
graph_medsug$microbe <- as.factor(graph_medsug$microbe)
graph_medsug$treatment <- as.factor(graph_medsug$treatment)

graph_medsug$time <- (seq.int(nrow(d3)))*15



graph_medsug<- graph_medsug %>%
  group_by(well) %>% 
  mutate(value_adjust=value- first(value))

```



```{r graph, echo=FALSE}

ggplot(graph_2xaa, aes(x=time, y=value_adjust, color=treatment)) +
  geom_point(aes(), alpha=0.2) +
  facet_wrap(graph_2xaa$microbe ~ graph_2xaa$name + graph_2xaa$type, scales = "free_y") +
  theme_bw() +
  labs(title="2x AA")


ggplot(graph_highaa, aes(x=time, y=value_adjust, color=treatment)) +
  geom_point(aes(), alpha=0.5) +
  facet_wrap(graph_highaa$microbe ~ graph_highaa$name + graph_highaa$type, scales = "free_y") +
  theme_bw() +
  labs(title="10x AA")


ggplot(graph_medsug, aes(x=time, y=value_adjust, color=treatment)) +
  geom_point(aes(), alpha=0.5) +
  facet_wrap(graph_medsug$microbe ~ graph_medsug$name + graph_medsug$type, scales = "free_y") +
  theme_bw()+
  labs(title="2x sugar")


```




```{r parameter plots, echo=FALSE}



parms_2xaa$treatment <- as.factor(parms_2xaa$treatment)
parms_2xaa$microbe <- as.factor(parms_2xaa$microbe)

#plot mu
ggplot(parms_2xaa, aes(x=treatment, y=mu.model, color=treatment)) +
  geom_boxplot(aes(), alpha=0.5) +
  geom_point(aes(), size=.5) +
  theme(axis.text.x=element_text(angle = -70, hjust = 0)) +
  labs(title = "2x aa growthrate") +
  facet_wrap(parms_2xaa$microbe, scales = "free_y")



#plot A
ggplot(parms_2xaa, aes(x=treatment, y=A.model, color=treatment)) +
  geom_boxplot(aes(), alpha=0.5) +
  geom_point(aes(), size=.5) +
  theme(axis.text.x=element_text(angle = -70, hjust = 0))+
  labs(title = "2x aa carry capacity")+
  facet_wrap(parms_2xaa$microbe, scales = "free_y")



#plot lambda
ggplot(parms_2xaa, aes(x=treatment, y=lambda.model, color=treatment)) +
  geom_boxplot(aes(), alpha=0.5) +
  geom_point(aes(), size=.5) +
  theme(axis.text.x=element_text(angle = -70, hjust = 0))+
  labs(title = "2x aa lag time")+
  facet_wrap(parms_2xaa$microbe, scales = "free_y")




parms_highaa$treatment <- as.factor(parms_highaa$treatment)
parms_highaa$microbe <- as.factor(parms_highaa$microbe)


ggplot(parms_highaa, aes(x=treatment, y=mu.model, color=treatment)) +
  geom_boxplot(aes(), alpha=0.5) +
  geom_point(aes(), size=.5) +
  theme(axis.text.x=element_text(angle = -70, hjust = 0)) +
  labs(title = "high aa growthrate") +
  facet_wrap(parms_highaa$microbe, scales = "free_y")



#plot A
ggplot(parms_highaa, aes(x=treatment, y=A.model, color=treatment)) +
  geom_boxplot(aes(), alpha=0.5) +
  geom_point(aes(), size=.5) +
  theme(axis.text.x=element_text(angle = -70, hjust = 0))+
  labs(title = "high aa carry capacity")+
  facet_wrap(parms_highaa$microbe, scales = "free_y")



#plot lambda
ggplot(parms_highaa, aes(x=treatment, y=lambda.model, color=treatment)) +
  geom_boxplot(aes(), alpha=0.5) +
  geom_point(aes(), size=.5) +
  theme(axis.text.x=element_text(angle = -70, hjust = 0))+
  labs(title = "high aa lag time")+
  facet_wrap(parms_highaa$microbe, scales = "free_y")



parms_medsug$treatment <- as.factor(parms_medsug$treatment)
parms_medsug$microbe <- as.factor(parms_medsug$microbe)

ggplot(parms_medsug, aes(x=treatment, y=mu.model, color=treatment)) +
  geom_boxplot(aes(), alpha=0.5) +
  geom_point(aes(), size=.5) +
  theme(axis.text.x=element_text(angle = -70, hjust = 0)) +
  labs(title = "med sugar growthrate") +
  facet_wrap(parms_medsug$microbe, scales = "free_y")


#plot A
ggplot(parms_medsug, aes(x=treatment, y=A.model, color=treatment)) +
  geom_boxplot(aes(), alpha=0.5) +
  geom_point(aes(), size=.5) +
  theme(axis.text.x=element_text(angle = -70, hjust = 0))+
  labs(title = "med sugar carry capacity")+
  facet_wrap(parms_medsug$microbe, scales = "free_y")



#plot lambda
ggplot(parms_medsug, aes(x=treatment, y=lambda.model, color=treatment)) +
  geom_boxplot(aes(), alpha=0.5) +
  geom_point(aes(), size=.5) +
  theme(axis.text.x=element_text(angle = -70, hjust = 0))+
  labs(title = "med sugar lag time")+
  facet_wrap(parms_medsug$microbe, scales = "free_y")











```









``` {r dilution curve,  echo=FALSE}



setwd("C:/Users/obiew/Desktop/vannette/dilution_curve")

library(ggplot2)
library(gridExtra)
library(tidyverse)
library(ggallin)



d <- read.csv("input/dilution_cfus.csv")

  

#subset data for type, then make quick lm
y <- filter(d, strain == c("ec52"))
y <- rename(y, c("cfu_yeast" = "cfu"))
b <- filter(d, strain == c("bb362"))
b <- rename(b, c("cfu_bact" = "cfu"))

lmy<-  lm(data= y, cfu_yeast~cells)
lmb<-  lm(data= b, cfu_bact~cells)



ggplot(d, aes(x=cells, y=cfu, color=strain)) +
  geom_point(aes()) +
  stat_smooth(method = "lm", fullrange = TRUE)+
  theme(axis.text.x=element_text(angle = -70, hjust = 0))+
  labs(title = "cfus by cells plated") +
  geom_hline(yintercept =0)+
  geom_vline(xintercept =1)+
  labs(title = paste(
       "Adj R2 bb362 = ",signif(summary(lmb)$adj.r.squared, 5),
       "Intercept bb362=",signif(lmb$coef[[1]],5 ),
       "Slope bb362=",signif(lmb$coef[[2]], 5),
       " P bb362=",signif(summary(lmb)$coef[2,4], 5), 
       "\n Adj R2 ec52 = ",signif(summary(lmy)$adj.r.squared, 5),
       "Intercept ec52=",signif(lmy$coef[[1]],5 ),
       " Slope ec52=",signif(lmy$coef[[2]], 5),
       " P ec52=",signif(summary(lmy)$coef[2,4], 5)))
```








